/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'error':                    '#ffb4ab',
        'on-secondary-fixed-variant':'#474746',
        'on-tertiary-fixed':        '#001f23',
        'secondary-fixed':          '#e4e2e1',
        'on-tertiary-fixed-variant':'#004f56',
        'on-surface-variant':       '#9a9077',
        'on-primary-container':     '#6f5a00',
        'on-secondary-container':   '#b6b5b4',
        'secondary-fixed-dim':      '#c8c6c5',
        'secondary':                '#c8c6c5',
        'outline-variant':          '#393428',
        'on-secondary-fixed':       '#1b1c1c',
        'on-surface':               '#ebe2cf',
        'primary-fixed':            '#ffe07f',
        'inverse-on-surface':       '#353024',
        'surface-bright':           '#3e392c',
        'tertiary-container':       '#0bebff',
        'primary':                  '#fff1ce',
        'tertiary':                 '#d0f9ff',
        'surface-tint':             '#edc200',
        'on-error':                 '#690005',
        'tertiary-fixed':           '#8df2ff',
        'surface-dim':              '#171309',
        'primary-fixed-dim':        '#edc200',
        'surface-container-low':    '#110e05',
        'surface-variant':          '#1f1b10',
        'on-primary':               '#3c2f00',
        'on-primary-fixed':         '#231b00',
        'on-primary-fixed-variant': '#564500',
        'on-background':            '#ebe2cf',
        'on-error-container':       '#ffdad6',
        'surface':                  '#0a0a0a',
        'surface-container':        '#171309',
        'inverse-primary':          '#725c00',
        'surface-container-lowest': '#050505',
        'on-secondary':             '#303030',
        'primary-container':        '#ffd100',
        'surface-container-high':   '#231f14',
        'error-container':          '#93000a',
        'background':               '#0a0a0a',
        'on-tertiary':              '#00363c',
        'tertiary-fixed-dim':       '#00dbed',
        'surface-container-highest':'#2e2a1e',
        'outline':                  '#4d4632',
        'secondary-container':      '#474746',
        'on-tertiary-container':    '#006670',
        'inverse-surface':          '#ebe2cf',
        'industrial-red':           '#FF3B30',
        'industrial-green':         '#34C759',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg:     '0px',
        xl:     '0px',
        full:   '9999px',
      },
      spacing: {
        'unit':           '4px',
        'panel-gap':      '12px',
        'gutter':         '20px',
        'margin-mobile':  '16px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        'display-lg':  ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-std':    ['Inter', 'sans-serif'],
        'label-caps':  ['Inter', 'sans-serif'],
        'metric-lg':   ['JetBrains Mono', 'monospace'],
        'body-fixed':  ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg':  ['40px',  { lineHeight: '1.1',  letterSpacing: '-0.01em', fontWeight: '900' }],
        'headline-md': ['20px',  { lineHeight: '1.2',  fontWeight: '700' }],
        'body-std':    ['15px',  { lineHeight: '1.6',  fontWeight: '400' }],
        'label-caps':  ['11px',  { lineHeight: '16px', letterSpacing: '0.1em',   fontWeight: '600' }],
        'metric-lg':   ['28px',  { lineHeight: '1',    letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-fixed':  ['13px',  { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
